---
machine:
  environment:
    maxMemoryAlloted: 500
  services:
    - redis
  node:
    version: 8

dependencies:
  post:
    - case $CIRCLE_NODE_INDEX in 0) NODE_VERSION=8 ;; 1) NODE_VERSION=9;; esac; nvm install $NODE_VERSION && nvm alias default $NODE_VERSION
    - node --version
    - npm --version
    - npm install
    - npm rebuild

test:
  override:
    - "echo Node Version: `node --version` && npm test":
        parallel: true

general:
  branches:
    ignore:
      - gh-pages

deployment:
  production:
    branch: master
    commands:
      - bin/deploy-docs
