#!/usr/bin/env node

console.log("**********");
console.log("You have installed actionHero!");
console.log("run `npm run-script actionHero generate` in an empty directoy to generate a template project");
console.log("**********");